backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "Página Principal"
    files:
      - file: "data/home.json"
        label: "Contenido Principal"
        name: "home"
        fields:
          - { label: "Título Principal (Hero)", name: "hero_title", widget: "string" }
          - { label: "Subtítulo (Descripción)", name: "hero_subtitle", widget: "string" }
          - { label: "Imagen de Fondo (Hero)", name: "hero_background", widget: "image" }
          - label: "Galería"
            name: "gallery"
            widget: "list"
            fields:
              - { label: "Imagen", name: "image", widget: "image" }
              - { label: "Descripción", name: "alt", widget: "string", required: false }
